language: objective-c
xcode_project: PromiseKit.xcodeproj
xcode_scheme: [PMKOSX]
xcode_sdk: [macosx]
osx_image: xcode8
env: TOOLCHAINS=com.apple.dt.toolchain.Swift_2_3
install: carthage bootstrap --platform Mac
script: set -o pipefail && xcodebuild -scheme PMKOSX test | xcpretty
