os: osx
language: swift
osx_image: xcode10.2

branches:
  only:
    - v7
    - master
    - v6
    - v4
    - legacy-1.x
    - /^\d+\.\d+\.\d+$/

stages:
  - name: pretest
  - name: test
  - name: deploy
    if: branch =~ ^\d+\.\d+\.\d+$

os: osx
osx_image: xcode10.2
language: swift
xcode_project: PromiseKit.xcodeproj
xcode_scheme: PromiseKit-Package
xcode_destination: 'platform=macOS'

jobs:
  include:
    - stage: pretest
      name: Validate Linux test coverage completeness
      install: swift test --generate-linuxmain
      script: git diff --exit-code

    - &test
      name: macOS
      stage: test
      install: swift package generate-xcodeproj --enable-code-coverage
      after_success: bash <(curl -s https://codecov.io/bash)
    - <<: *test
      name: iOS
      xcode_destination: 'OS=12.2,name=iPhone SE'
    - <<: *test
      name: tvOS
      xcode_destination: 'OS=12.2,name=Apple TV'

    - name: Linux
      env: SWIFT_VERSION='5.0-DEVELOPMENT-SNAPSHOT-2019-01-22-a'
      os: linux
      language: generic
      osx_image: null
      install: eval "$(curl -sL https://swiftenv.fuller.li/install.sh)"
      script: swift test

    - name: JavaScript Promises/A+
      install: |
        bash -c "
          cd Tests/A+/JavaScript
          npm ci &>/dev/null
          npm run --hide-modules build"
      script: swift test --filter A__js.AllTests
      after_success: bash <(curl -s https://codecov.io/bash)
      cache.directories:
        - Tests/JS-A+/build
        - Tests/JS-A+/node_modules

    - name: '`pod trunk push`'
      stage: deploy
      install: gem install cocoapods --pre -v 1.7.0.beta.3
      before_script: |
        mv .github/PromiseKit.podspec .
        sed -i '' "s/s.version = '0.0.1'/s.version = '$TRAVIS_TAG'/g" PromiseKit.podspec
      script: |
        set -exo pipefail
        pod trunk push --verbose --allow-warnings | tee pod.log | ruby -e 'ARGF.each{ print "." }'
      # ^^ pipe because Travis times us out if there is no output
      # AND `pod` defaults to hardly any output
      # BUT `--verbose` generates so much output that Travis kills our script due to *too much* output!
      # --allow-warnings because Bolts generates warnings and CocoaPods fails you even if your deps emit warnings
      after_failure: cat pod.log | grep error

    - name: Generate Documentation
      git.depth: false
      install: gem install jazzy
      script: |
        set -exo pipefail
        jazzy --config .github/jazzy.yml \
              --github_url "https://github.com/$TRAVIS_REPO_SLUG" \
              --module-version "$TRAVIS_TAG"
        git remote update
        git fetch origin gh-pages:gh-pages --depth 1
        git checkout gh-pages
        rm -rf reference/v7
        mv foo reference/v7
        git add reference/v7
        git config user.name  "Travis"
        git config user.email "jazzy@travis-ci.com"
        git commit -m "Updated docs for v$TRAVIS_TAG"
        git remote add secure-origin https://${GITHUB_TOKEN}@github.com/$TRAVIS_REPO_SLUG.git
        git push secure-origin gh-pages
